export const GET_MOVIES_LIST = 'GET_MOVIES_LIST';
export const FILTER_MOVIES_LIST = 'FILTER_MOVIES_LIST';
export const GET_MOVIES_LIST_PART_2 = 'GET_MOVIES_LIST_PART_2';
export const GET_MOVIES_LIST_PART_3 = 'GET_MOVIES_LIST_PART_3';
